[2025-07-03T02:38:42.142Z] [ERROR] FATAL: Uncaught Exception | {"error":"write EPIPE","stack":"Error: write EPIPE\n    at afterWriteDispatched (node:internal/stream_base_commons:159:15)\n    at writeGeneric (node:internal/stream_base_commons:150:3)\n    at Socket._writeGeneric (node:net:966:11)\n    at Socket._write (node:net:978:8)\n    at writeOrBuffer (node:internal/streams/writable:570:12)\n    at _write (node:internal/streams/writable:499:10)\n    at Writable.write (node:internal/streams/writable:508:10)\n    at console.value (node:internal/console/constructor:298:16)\n    at console.log (node:internal/console/constructor:384:26)\n    at Logger.log (/home/neifui/Documents/OnluyenVatLy/api/utils/logger.js:35:13)\n    at Logger.info (/home/neifui/Documents/OnluyenVatLy/api/utils/logger.js:48:10)\n    at Logger.logRequest (/home/neifui/Documents/OnluyenVatLy/api/utils/logger.js:91:10)\n    at ServerResponse.<anonymous> (/home/neifui/Documents/OnluyenVatLy/api/index.js:84:16)\n    at ServerResponse.emit (node:events:519:35)\n    at onFinish (node:_http_outgoing:1024:10)\n    at afterWrite (node:internal/streams/writable:708:5)"}
[2025-07-03T04:19:35.414Z] [ERROR] FATAL: Uncaught Exception | {"error":"write EPIPE","stack":"Error: write EPIPE\n    at afterWriteDispatched (node:internal/stream_base_commons:159:15)\n    at writeGeneric (node:internal/stream_base_commons:150:3)\n    at Socket._writeGeneric (node:net:966:11)\n    at Socket._write (node:net:978:8)\n    at writeOrBuffer (node:internal/streams/writable:570:12)\n    at _write (node:internal/streams/writable:499:10)\n    at Writable.write (node:internal/streams/writable:508:10)\n    at console.value (node:internal/console/constructor:298:16)\n    at console.log (node:internal/console/constructor:384:26)\n    at requireStudentAuthForHTML (/home/neifui/Documents/OnluyenVatLy/api/routes/views.js:27:11)\n    at Layer.handle [as handle_request] (/home/neifui/Documents/OnluyenVatLy/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/neifui/Documents/OnluyenVatLy/node_modules/express/lib/router/route.js:149:13)\n    at Route.dispatch (/home/neifui/Documents/OnluyenVatLy/node_modules/express/lib/router/route.js:119:3)\n    at Layer.handle [as handle_request] (/home/neifui/Documents/OnluyenVatLy/node_modules/express/lib/router/layer.js:95:5)\n    at /home/neifui/Documents/OnluyenVatLy/node_modules/express/lib/router/index.js:284:15\n    at param (/home/neifui/Documents/OnluyenVatLy/node_modules/express/lib/router/index.js:365:14)"}
[2025-07-03T04:32:59.891Z] [ERROR] FATAL: Uncaught Exception | {"error":"listen EADDRINUSE: address already in use :::3003","stack":"Error: listen EADDRINUSE: address already in use :::3003\n    at Server.setupListenHandle [as _listen2] (node:net:1940:16)\n    at listenInCluster (node:net:1997:12)\n    at Server.listen (node:net:2102:7)\n    at app.listen (/home/neifui/Documents/OnluyenVatLy/node_modules/express/lib/application.js:635:24)\n    at Object.<anonymous> (/home/neifui/Documents/OnluyenVatLy/api/index.js:221:20)\n    at Module._compile (node:internal/modules/cjs/loader:1734:14)\n    at Object..js (node:internal/modules/cjs/loader:1899:10)\n    at Module.load (node:internal/modules/cjs/loader:1469:32)\n    at Module._load (node:internal/modules/cjs/loader:1286:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:152:5)\n    at node:internal/main/run_main_module:33:47"}
[2025-07-03T04:34:52.860Z] [ERROR] FATAL: Uncaught Exception | {"error":"write EPIPE","stack":"Error: write EPIPE\n    at afterWriteDispatched (node:internal/stream_base_commons:159:15)\n    at writeGeneric (node:internal/stream_base_commons:150:3)\n    at Socket._writeGeneric (node:net:966:11)\n    at Socket._write (node:net:978:8)\n    at writeOrBuffer (node:internal/streams/writable:570:12)\n    at _write (node:internal/streams/writable:499:10)\n    at Writable.write (node:internal/streams/writable:508:10)\n    at console.value (node:internal/console/constructor:298:16)\n    at console.log (node:internal/console/constructor:384:26)\n    at Logger.log (/home/neifui/Documents/OnluyenVatLy/api/utils/logger.js:35:13)\n    at Logger.info (/home/neifui/Documents/OnluyenVatLy/api/utils/logger.js:48:10)\n    at Logger.logRequest (/home/neifui/Documents/OnluyenVatLy/api/utils/logger.js:91:10)\n    at ServerResponse.<anonymous> (/home/neifui/Documents/OnluyenVatLy/api/index.js:84:16)\n    at ServerResponse.emit (node:events:519:35)\n    at onFinish (node:_http_outgoing:1024:10)\n    at afterWrite (node:internal/streams/writable:708:5)"}
[2025-07-03T04:45:24.613Z] [ERROR] FATAL: Uncaught Exception | {"error":"listen EADDRINUSE: address already in use :::3003","stack":"Error: listen EADDRINUSE: address already in use :::3003\n    at Server.setupListenHandle [as _listen2] (node:net:1940:16)\n    at listenInCluster (node:net:1997:12)\n    at Server.listen (node:net:2102:7)\n    at app.listen (/home/neifui/Documents/OnluyenVatLy/node_modules/express/lib/application.js:635:24)\n    at Object.<anonymous> (/home/neifui/Documents/OnluyenVatLy/api/index.js:221:20)\n    at Module._compile (node:internal/modules/cjs/loader:1734:14)\n    at Object..js (node:internal/modules/cjs/loader:1899:10)\n    at Module.load (node:internal/modules/cjs/loader:1469:32)\n    at Module._load (node:internal/modules/cjs/loader:1286:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:152:5)\n    at node:internal/main/run_main_module:33:47"}
